configlet: fix example uuid command (#44)
This should be a long option.

Previously this command caused an error, because `um` was parsed as an
argument to the `-n` option:
```
$ configlet uuid -num 5
Error: value for '-n' is not a positive integer: um
```

Abbreviated usage for configlet:
```
Usage:
  configlet [global-options] <command> [command-options]

Commands:
  lint, sync, uuid

Options for uuid:
  -n, --num <int>              Number of UUIDs to generate
```